remote_theme: jekyll-theme-minimal
description: welcome
# Site wide configuration

title: Chema Rodriguez
date_format: "%b %-d, %Y"
social_links:
  github:  jmroval
  linkedIn: in/josé-maría-rodríguez-valadez-157b0680/ # format: locale/username
theme: jekyll-theme-minimal
